// Generated by typings
// Source: 
// Type definitions for http-auth 2.3.3
// Project: https://github.com/http-auth/http-auth
// Definitions by: Jussi Kinnula <https://github.com/jussikinnula/>
// Definitions: https://github.com/jussikinnula/DefinitelyTyped

interface HttpAuthParams {
    realm?: string;
    file?: string;
}

interface HttpAuthCallback {
    (username: string, password: string, callback: any): void;
}

declare module 'http-auth' {
    export function basic(params?: HttpAuthParams, callback?: HttpAuthCallback): any;
    export function connect(basic: any): any;
}
